# 从各个模型文件导入图像生成函数
from utils.models.ali_generator import generate_image_ali
from utils.models.baidu_generator import generate_image_baidu
from utils.models.zhipu_generator import generate_image_zhipu
from utils.models.xunfei_generator import generate_image_xunfei
from utils.models.claude_generator import generate_image_claude
from utils.models.gpt_generator import generate_image_gpt
from utils.models.deepseek_generator import generate_image_deepseek
from utils.models.silicon_generator import generate_image_silicon
