# 从各个模型文件导入文本生成函数
from utils.models.ali_generator import generate_text_ali
from utils.models.baidu_generator import generate_text_baidu
from utils.models.zhipu_generator import generate_text_zhipu
from utils.models.xunfei_generator import generate_text_xunfei
from utils.models.claude_generator import generate_text_claude
from utils.models.gpt_generator import generate_text_gpt
from utils.models.deepseek_generator import generate_text_deepseek
from utils.models.silicon_generator import generate_text_silicon
